// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl0PIxDsn_uT4b4wxIX46m9iTw4St24S8',
    appId: '1:762912282097:web:424508ccbc8a3d8c2e6050',
    messagingSenderId: '762912282097',
    projectId: 'notes-app-f968a',
    authDomain: 'notes-app-f968a.firebaseapp.com',
    storageBucket: 'notes-app-f968a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaxIZV4S8ttQi6FodVZWykwwXG7GW62mk',
    appId: '1:762912282097:android:194156621b6797162e6050',
    messagingSenderId: '762912282097',
    projectId: 'notes-app-f968a',
    storageBucket: 'notes-app-f968a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTBuUa4zJa2nCU30YDhadp_z6IGmpnweg',
    appId: '1:762912282097:ios:a5b399e645639dc72e6050',
    messagingSenderId: '762912282097',
    projectId: 'notes-app-f968a',
    storageBucket: 'notes-app-f968a.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

}